# Generated by Django 2.2.7 on 2019-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_album_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
