# Generated by Django 2.2.7 on 2019-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_album_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(to='search.Singer'),
        ),
    ]
