# Generated by Django 2.2.7 on 2019-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_song_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='search.Genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='search.Genre'),
        ),
    ]
