# Generated by Django 2.2.7 on 2019-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191126_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singers',
        ),
    ]
