# Generated by Django 3.0 on 2019-12-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20191127_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='singer',
            name='avatar_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='singer',
            name='poster_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='search.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='singers',
            field=models.ManyToManyField(related_name='albums', to='search.Singer'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='search.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='search.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(related_name='songs', to='search.Singer'),
        ),
    ]
